refactor(yaml): 🔍  we want live security updates
storyofams/next-api-decorators pull request #63
Opened 2021-03-17 08:16 UTC by mitchelvanbever

2021-03-17 08:16 UTC, mitchelvanbever commented
This should do the trick. We couild also add default labels, branch name and/or reviewers if prefered.

2021-03-17 17:43 UTC, ggurkal requested changes

2021-03-17 17:43 UTC, ggurkal commented on .github/dependabot.yml
> +  - package-ecosystem: "yarn"
i tried `yarn` before, but apparently it's not valid. should be set back to `npm`.

2021-03-17 17:47 UTC, ggurkal commented
The config becomes a mix of v1 and v2, so we will get errors. Validation can be done here: https://dependabot.com/docs/config-file/validator/

I'm a bit confused about dependabot as those two versions work quite different than each other. The changes are for v1 but I don't know if it's possible to use v1 with github as is. 🤔

2021-03-19 11:56 UTC, ggurkal commented
Seems like github supports only v2, which I believe doesn't create PRs only security updates. At least I couldn't find it...

2021-03-19 17:41 UTC, ggurkal commented
@mitchelvanbever seems like v1 is not supported anymore. so we have to revert the changes, but we can make some additions, like settings `beta` as the branch.

we can also try settings `versioning-strategy: increase-if-necessary` to see if it works as _security updates_.

2021-03-19 20:55 UTC, mitchelvanbever commented
> @mitchelvanbever seems like v1 is not supported anymore. so we have to revert the changes, but we can make some additions, like settings `beta` as the branch.
> 
> we can also try settings `versioning-strategy: increase-if-necessary` to see if it works as _security updates_.

Okay let's revert the changes and try that approach. I did also enable the dependebot-preview thingy for all repo's that are not managed through vercel, so maybe we don't even need the yml.

2021-03-24 14:40 UTC, merged